<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_documents = $this->getDocuments(); ?>
<div class="page-title title-buttons">
    <h1><?php echo $this->__('My Documents') ?></h1>
    <button type="button" title="<?php echo $this->__('Add New Document') ?>" class="button" onclick="window.location='<?php echo $this->getAddDocumentUrl() ?>';">
        <span><span><?php echo $this->__('Add New Document') ?></span></span>
    </button>
</div>
<?php echo $this->getPagerHtml(); ?>
<?php if($_documents->getSize()): ?>
<table class="data-table" id="my-documents-table">
    <col />
    <col />
    <col />
    <col />
    <col />
    <?php //<col width="1" /> ?>
    <thead>
        <tr>
            <th><?php echo $this->__('Document Name') ?></th>
            <th><?php echo $this->__('File Type') ?></th>
            <th><?php echo $this->__('Description') ?></th>
            <th><span class="nobr"><?php echo $this->__('Filename') ?></span></th>
            <th><span class="nobr"><?php echo $this->__('Approval Status') ?></span></th>
            <?php //<th>&nbsp;</th> ?>
        </tr>
    </thead>
    <tbody>
        <?php $_odd = ''; ?>
        <?php foreach ($_documents as $_document):?>
        <tr>
            <td><a href="<?php echo Mage::getUrl('*/*/edit', array('id' => $_document->getDocumentId()));?>"><?php echo $_document->getFile_name() ?></a></td>
            <td><span class="nobr"><?php echo $this->getFileTypeToName($_document->getFile_type()) ?></span></td>
            <td><?php echo $_document->getFile_description() ?></td>
            <td>
                <a data-href="/documents/index/download/filehash/<?php echo $_document->getFilehash(); ?>" target="_blank">
                    <?php echo $_document->getFilepath(); ?>
                </a>
            </td>
            <td>
                <em>
                    <?php echo $_document->getApproved() == 1 ?
                        '<span style="color:#092; font-style:normal !important;">' . $this->getFileStatusToName($_document->getApproved()) . '</span>' :
                        $this->getFileStatusToName($_document->getApproved()) ?>
                </em>
            </td>
            <?php /*<td class="a-center">
                <span class="nobr">
                	<a href="<?php echo $this->getDocumentEditUrl($_document) ?>"><?php echo $this->__('View') ?></a>
                </span>
            </td> */?>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('my-documents-table');</script>
<?php echo $this->getPagerHtml(); ?>
<?php else: ?>
    <p><?php echo $this->__('You have placed no documents.'); ?></p>
<?php endif ?>
<script type="text/javascript">
    jQuery('a[data-href]').on('click', function(e) {
        e.preventDefault();
        window.location.href = jQuery(this).data('href');
    });
</script>
<style>
    a {
        text-decoration: underline;
        cursor: pointer;
    }
</style>
<script language="javascript">
    jQuery(document).ready(function() {
       jQuery(document).bind("contextmenu",function(e){
           return false;
       });
    });
</script>